Add project_id and tag parameters to wordpress/*/build.

diff --git a/wordpress/deployer/build b/wordpress/deployer/build
--- a/wordpress/deployer/build
+++ b/wordpress/deployer/build
@@ -1,10 +1,45 @@
 #!/bin/bash
+#
+# Copyright 2018 Google LLC
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 set -e
 
+for i in "$@"
+do
+case $i in
+  --project_id=*)
+    project_id="${i#*=}"
+    shift
+    ;;
+  --tag=*)
+    tag="${i#*=}"
+    shift
+    ;;
+  *)
+    >&2 echo "Unrecognized flag: $i"
+    exit 1
+    ;;
+esac
+done
+
+[[ -z "$project_id" ]] && >&2 echo "--project_id required" && exit 1
+[[ -z "$tag" ]] && >&2 echo "--tag required" && exit 1
+
 docker build \
-  --build-arg "REGISTRY=gcr.io/$PROJECT_ID/" \
+  --build-arg "REGISTRY=gcr.io/$project_id/" \
   --build-arg TAG=latest \
-  --tag "gcr.io/$PROJECT_ID/example/wordpress/deployer:local" \
+  --tag "gcr.io/$project_id/example/wordpress/deployer:$tag" \
   --file deployer/Dockerfile \
   .
